language: node_js
sudo: false

node_js:
  - '10.16'
  - 'lts/*'

script:
  - npm test
  - codecov
#deploy:
#- provider: npm
#api_key: "YOUR_API_KEY"
#secret_access_key:
#secure: "Encypted <secret-access-key>"
#email: "email@domain.com"
#on: master
